tmux:
    symbols:
        branch: " "
        hashprefix: ":"
        ahead: ↑
        behind: ↓
        staged: "+"
        conflict: "~"
        modified: "!"
        untracked: "?"
        stashed: "*"
        clean: "✓"

    styles:
        clear: "#[none]"
        state: "#[fg=#e06c75,bold]"
        branch: "#[fg=#c678dd,bold]"
        remote: "#[fg=#56b6c2]"
        divergence: "#[fg=#98c379,bold]"
        staged: "#[fg=#98c379,bold]"
        conflict: "#[fg=#e06c75,bold]"
        modified: "#[fg=#e06c75,bold]"
        untracked: "#[fg=#e06c75,bold]"
        stashed: "#[fg=#56b6c2,bold]"
        clean: "#[fg=#98c379,bold]"

    layout: [branch, divergence, " ", flags]

    options:
        branch_max_len: 30
        branch_trim: right
        ellipsis: …
        hide_clean: true
