#!/bin/sh
case "$1" in
    lock)
        ~/Dotfiles/config/i3/scripts/lock.sh
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {kill|lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac
